### ISSUE TITLE
Panic when an channel is closed but expected to receive a message

### ISSUE THREAD

**Issue by joernlenoch** [cskr/pubsub#14]
Hi,

We apopted you tool a while ago to use as a central cornerstone in out internal event messaging system.

We work with a lot of potentially volatile channels (~600-1000 real time connections), resulting an the luckily rare error that an channel has been closed and removed before a message may reach it. This causes a system wide panic even though it could be easily ignored and discarded.

Nevertheless, this is a highly critical problem for us!

Therefore, I wanted to ask you whether you can add additional error handling or a discard recovery into the **publish** methods

I can provide a simple fix it you like.

**Comment by joernlenoch** [comment]
Additionally, it's seems to be a general problem with multithreaded environments.

**Comment by sunanxiang** [comment]
I think this isn't the pub/sub system's bug. This is a familiar bug when you use channel in go. When you  send message to a closed channel will result in this panic. So, when you close channel or quit program, you should unsub all topics. @joernlenoch

**Comment by cskr** [comment]
@joernlenoch Sorry about the extremely delayed response to this issue.

I don't fully understand the problem at hand. Do you still face the issue? If so, do you use [`AddSub`](https://godoc.org/github.com/cskr/pubsub#PubSub.AddSub) and then close the channel in your code instead of using [`Unsub`](https://godoc.org/github.com/cskr/pubsub#PubSub.Unsub)? Can you provide a sample code that is similar to what you're doing in your production system?

**Comment by joernlenoch** [comment]
I am very sorry for the massive delay - I will close this issue for now until I can fully verify that my issue still exists.
