### ISSUE TITLE
AddSub + Unsub closes my channels

### ISSUE THREAD

**Issue by robbrit** [cskr/pubsub#8]
I'm using a pattern where I have a communication channel that I use for a goroutine, and that channel is used to subscribe to a topic:

```
comms := make(chan interface{})
go func() {
  for msg := range comms {
    // do some stuff
  }
}()

mySub.AddSub(comms, "some-topic")
```

The problem is now and then I change the topic that I'm interested in (in my code, it's when users move from one room to another room):

```
mySub.Unsub(comms, "some-topic")
mySub.AddSub(comms, "some-other-topic")
```

Unsub will close my channel if "some-topic" is the only topic that I'm listening to. Is there a way so that when unsubscribing, the pubsub lib doesn't automatically close my channel? I can't reverse the order of the Unsub/AddSub since in reality the code is a bit more asynchronous than the example above.

The workaround for now is to create a dummy topic that all channels are subscribed to but never actually broadcasts anything.

**Comment by andrewhamon** [comment]
@robbrit could you also change topic by simply subscribing to the new topic first, so that the subscription count never drops to 0?

I do agree though, closing the channel during an unsubscribe was surprising to me, particularly if the channel was created by me and not given to me from the pubsub API.

On the other hand, I understand that there isn't an API exposed to determine what topics a channel is subscribed to, and I can easily imagine use cases where it would be desirable to close the channel when subscriptions drop to 0.

**Comment by cskr** [comment]
The idea behind closing the channel after unsubscribing from all topics was to ensure that subscribed goroutines don't end-up waiting forever.

If you don't have information about old and new rooms at the same time, you can check whether the subscription channel has been closed and create a new one.
